# Generated by Django 4.2.7 on 2024-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration_test',
            field=models.IntegerField(default=0),
        ),
    ]
