# Generated by Django 4.2.7 on 2024-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('unique_code', models.CharField(max_length=6, unique=True)),
                ('duration_test', models.IntegerField(default=0)),
            ],
        ),
    ]
