# Generated by Django 4.2.7 on 2024-04-18 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_test_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
